### ISSUE TITLE
can we have GAFF-version with charged atoms

### ISSUE THREAD

**Issue by thangckt** [rsdefever/GAFF-foyer#13]
Dear Developers, 

all of the partial charges in the GAFF XML are set to 0.0
Can you fill them with atomic charges?

Thank.

**Comment by rsdefever** [comment]
The partial charges are set to zero in the GAFF XML because the [GAFF force field](https://onlinelibrary.wiley.com/doi/10.1002/jcc.20035) specifies that partial charges are determined on a per-molecule basis with RESP.
